export const FETCH_CURRENCIES_RATES: string = 'FETCH_CURRENCIES_RATES';
export const FETCH_CURRENCIES: string = 'FETCH_CURRENCIES';
export const CHANGE_EXCHANGER_RATES: string = 'CHANGE_EXCHANGER_RATES';
export const CHANGE_EXCHANGED_RATES: string = 'CHANGE_EXCHANGED_RATES';
export const CHANGE_EXCHANGER_CURRENCY: string = 'CHANGE_EXCHANGER_CURRENCY';
export const CHANGE_EXCHANGED_CURRENCY: string = 'CHANGE_EXCHANGED_CURRENCY';
export const SWAP_CURRENCIES: string = 'SWAP_CURRENCIES';
